In [24]:
import sqlite3
import pandas as pd
import numpy as np

In [25]:
conn = sqlite3.connect('shopee.db')
query = 'SELECT * FROM items'

df = pd.read_sql_query(query, conn)

In [26]:
df.head()

,id,shop_id,name,stock,sold,liked,comment,status,price,price_min,price_max,discount,rating_1,rating_2,rating_3,rating_4,rating_5
0,8535475240,104741119,Áo Lót Nam Cotton W&W Áo Thun Trắng Cộc Tay Ch...,198,477,83,82,normal,105000,105000,152500,50,1,0,1,4,76
1,11608442526,104741119,"Quần Đùi Ngủ Mặc Nhà Nam W&W Cạp Chun, Chất Li...",798,303,731,70,normal,54500,54500,163500,50,2,2,2,7,57
2,6190848264,104741119,Áo Thun Nam Polo W&W Dáng Regular Fit- Cổ Đức ...,26,53,705,19,normal,212500,212500,212500,50,0,0,1,0,18
3,8772409270,104741119,Combo Áo Lót Nam Ba Lỗ WW Màu Trắng Chất Liệu ...,62,271,731,76,normal,95000,95000,285000,0,0,0,1,2,73
4,2937465699,104741119,"Áo Thun Tanktop Nam WW Siêu Mát, Thấm Hút Mồ H...",11,101,693,29,normal,87500,87500,87500,50,1,0,0,3,25

In [34]:
df[df['name'].str.contains('sơ mi')]

,id,shop_id,name,stock,sold,liked,comment,status,price,price_min,price_max,discount,rating_1,rating_2,rating_3,rating_4,rating_5
80,16086121635,111639450,Áo sơ mi nhung tăm thêu PATTERN PA016,355,2552,852,707,normal,199000,199000,199000,44,1,3,16,49,638
94,3683529574,111639450,Áo sơ mi họa tiết PATTERN Cuban shirt hoa lá đ...,47,4350,1166,935,normal,169000,169000,169000,43,5,7,11,52,860
101,22042552184,111639450,Bộ sơ mi đũi nhăn PATTERN PB007,18,2,4,0,normal,269000,269000,269000,46,0,0,0,0,0
107,12693524965,111639450,Áo sơ mi nam cộc tay PATTERN Cuban shirt 5 màu...,87,2195,1118,587,normal,169000,169000,169000,43,6,4,10,52,515
1519,9461767378,24710134,Áo sơ mi nam dài tay Café Sticky Free khử mùi ...,785,1649,360,521,normal,499000,499000,499000,0,1,2,2,16,500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4398,14496322433,92937520,OWEN - Áo sơ mi dài tay Regular Fit màu Xanh N...,20,0,1,0,normal,650000,650000,650000,0,0,0,0,0,0
4399,14064158867,92937520,Áo sơ mi dài tay nam Owen Nano Regular Fit Xan...,11,1,1,0,normal,312400,312400,312400,45,0,0,0,0,0
4401,12894777108,92937520,Áo sơ mi ngắn tay Nam Owen Bamboo Body Fit Xan...,6,10,4,3,normal,568000,568000,568000,0,0,0,0,0,3
4405,11399358678,92937520,OWEN - Áo sơ mi dài tay Regular Fit Ghi Cafe T...,17,0,1,0,normal,690000,690000,690000,0,0,0,0,0,0
4408,10697665255,92937520,Áo sơ mi Nam dài tay Owen Slim Fit Nền ghi mel...,15,3,4,0,normal,598000,598000,598000,0,0,0,0,0,0